version: "3"
services:
  mongodb:
    image: mongo:4.4.12
    ports:
      - 27017:27017
    networks:
      - profileapp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    networks:
      - profileapp
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
networks:
  profileapp:
